export const START_FETCHING_HOME_CONTENT = 'START_FETCHING_HOME_CONTENT';
export const FETCHING_HOME_CONTENT_SUCCESS = 'FETCHING_HOME_CONTENT_SUCCESS';
export const FETCHING_HOME_CONTENT_FAILURE = 'FETCHING_HOME_CONTENT_FAILURE';


// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
