export const START_FETCHING_HOME_CONTENT = 'START_FETCHING_HOME_CONTENT';
export const FETCHING_HOME_CONTENT_SUCCESS = 'FETCHING_HOME_CONTENT_SUCCESS';
export const FETCHING_HOME_CONTENT_FAILURE = 'FETCHING_HOME_CONTENT_FAILURE';

export const HOME_SPINNER_STARTS = 'HOME_SPINNER_STARTS'
export const HOME_SPINNER_STOPS = 'HOME_SPINNER_STOPS'
export const START_FETCHING_HOME_CONTENT_WITH_SPINNER = 'START_FETCHING_HOME_CONTENT_WITH_SPINNER'


// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
