export const START_FETCHING_MEMBERSHIP_CONTENT = 'START_FETCHING_MEMBERSHIP_CONTENT';
export const FETCHING_MEMBERSHIP_CONTENT_SUCCESS = 'FETCHING_MEMBERSHIP_CONTENT_SUCCESS';
export const FETCHING_MEMBERSHIP_CONTENT_FAILURE = 'FETCHING_MEMBERSHIP_CONTENT_FAILURE';

export const MEMBERSHIP_SPINNER_STARTS = 'MEMBERSHIP_SPINNER_STARTS'
export const MEMBERSHIP_SPINNER_STOPS = 'MEMBERSHIP_SPINNER_STOPS'
export const START_FETCHING_MEMBERSHIP_CONTENT_WITH_SPINNER = 'START_FETCHING_MEMBERSHIP_CONTENT_WITH_SPINNER'
// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
