export const START_FETCHING_EVENT_CONTENT = 'START_FETCHING_EVENT_CONTENT';
export const FETCHING_EVENT_CONTENT_SUCCESS = 'FETCHING_EVENT_CONTENT_SUCCESS';
export const FETCHING_EVENT_CONTENT_FAILURE = 'FETCHING_EVENT_CONTENT_FAILURE';

export const EVENT_SPINNER_STARTS = 'EVENT_SPINNER_STARTS'
export const EVENT_SPINNER_STOPS = 'EVENT_SPINNER_STOPS'
export const START_FETCHING_EVENT_CONTENT_WITH_SPINNER = 'START_FETCHING_EVENT_CONTENT_WITH_SPINNER'

// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
