export const START_FETCHING_GETINVOLVED_CONTENT = 'START_FETCHING_GETINVOLVED_CONTENT';
export const FETCHING_GETINVOLVED_CONTENT_SUCCESS = 'FETCHING_GETINVOLVED_CONTENT_SUCCESS';
export const FETCHING_GETINVOLVED_CONTENT_FAILURE = 'FETCHING_GETINVOLVED_CONTENT_FAILURE';

export const GETINVOLVED_SPINNER_STARTS = 'GETINVOLVED_SPINNER_STARTS'
export const GETINVOLVED_SPINNER_STOPS = 'GETINVOLVED_SPINNER_STOPS'
export const START_FETCHING_GETINVOLVED_CONTENT_WITH_SPINNER = 'START_FETCHING_GETINVOLVED_CONTENT_WITH_SPINNER'
// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
