export const PUSH_NEWS_READER_PAGE= 'PUSH_NEWS_READER_PAGE';
export const PUSH_BLOGS_READER_PAGE= 'PUSH_BLOGS_READER_PAGE';
export const PUSH_ARTICLES_READER_PAGE= 'PUSH_ARTICLES_READER_PAGE';
export const PUSH_RESOURCES_READER_PAGE= 'PUSH_RESOURCES_READER_PAGE';
export const PUSH_PRESS_READER_PAGE= 'PUSH_PRESS_READER_PAGE';

export const PUSH_TEAM_READER_PAGE= 'PUSH_TEAM_READER_PAGE';
// export const PUSH_NEWS_READER_PAGE= 'PUSH_NEWS_READER_PAGE';

// export const STOP_FETCHING_SPINNER = 'STOP_FETCHING_SPINNER';

// export const START_AUTH_SPINNER= 'START_AUTH_SPINNER';
// export const STOP_AUTH_SPINNER = 'STOP_AUTH_SPINNER';

// export const START_POSTING_SPINNER= 'START_POSTING_SPINNER';
// export const STOP_POSTING_SPINNER = 'STOP_POSTING_SPINNER';
