export const START_FETCHING_PUBLICATION_CONTENT = 'START_FETCHING_PUBLICATION_CONTENT';
export const FETCHING_PUBLICATION_CONTENT_SUCCESS = 'FETCHING_PUBLICATION_CONTENT_SUCCESS';
export const FETCHING_PUBLICATION_CONTENT_FAILURE = 'FETCHING_PUBLICATION_CONTENT_FAILURE';

export const PUBLICATION_SPINNER_STARTS = 'PUBLICATION_SPINNER_STARTS'
export const PUBLICATION_SPINNER_STOPS = 'PUBLICATION_SPINNER_STOPS'
export const START_FETCHING_PUBLICATION_CONTENT_WITH_SPINNER = 'START_FETCHING_PUBLICATION_CONTENT_WITH_SPINNER'

// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
