export const START_FETCHING_FOOTER_CONTENT = 'START_FETCHING_FOOTER_CONTENT';
export const FETCHING_FOOTER_CONTENT_SUCCESS = 'FETCHING_FOOTER_CONTENT_SUCCESS';
export const FETCHING_FOOTER_CONTENT_FAILURE = 'FETCHING_FOOTER_CONTENT_FAILURE';

export const FOOTER_SPINNER_STARTS = 'FOOTER_SPINNER_STARTS'
export const FOOTER_SPINNER_STOPS = 'FOOTER_SPINNER_STOPS'
export const START_FETCHING_FOOTER_CONTENT_WITH_SPINNER = 'START_FETCHING_FOOTER_CONTENT_WITH_SPINNER'


// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
