export const START_FETCHING_SPINNER= 'START_FETCHING_SPINNER';
export const STOP_FETCHING_SPINNER = 'STOP_FETCHING_SPINNER';

export const START_AUTH_SPINNER= 'START_AUTH_SPINNER';
export const STOP_AUTH_SPINNER = 'STOP_AUTH_SPINNER';

export const START_POSTING_SPINNER= 'START_POSTING_SPINNER';
export const STOP_POSTING_SPINNER = 'STOP_POSTING_SPINNER';
