export const START_FETCHING_CONTACT_CONTENT = 'START_FETCHING_CONTACT_CONTENT';
export const FETCHING_CONTACT_CONTENT_SUCCESS = 'FETCHING_CONTACT_CONTENT_SUCCESS';
export const FETCHING_CONTACT_CONTENT_FAILURE = 'FETCHING_CONTACT_CONTENT_FAILURE';

export const CONTACT_SPINNER_STARTS = 'CONTACT_SPINNER_STARTS'
export const CONTACT_SPINNER_STOPS = 'CONTACT_SPINNER_STOPS'
export const START_FETCHING_CONTACT_CONTENT_WITH_SPINNER = 'START_FETCHING_CONTACT_CONTENT_WITH_SPINNER'
// export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
// export const USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE';
// export const GET_USER_ROLE = 'GET_USER_ROLE';
