// export const START_FETCHING_ALL_USERS = 'START_FETCHING_ALL_USERS';
// export const FETCHING_ALL_USERS_SUCCESS = 'FETCHING_ALL_USERS_SUCCESS';
// export const FETCHING_ALL_USERS_FAILURE = 'FETCHING_ALL_USERS_FAILURE';

// export const START_FETCHING_SINGLE_USER = 'START_FETCHING_SINGLE_USER';
// export const FETCHING_SINGLE_USER_SUCCESS = 'FETCHING_SINGLE_USER_SUCCESS';
// export const FETCHING_SINGLE_USER_FAILURE = 'FETCHING_SINGLE_USER_FAILURE';

export const UPDATE_USER = 'UPDATE_USER'


